Terraform 2
Otus-DevOps-22-08/sajor2006_infra pull request #8
Opened 2022-12-09 17:07 UTC by sajor2006

# Выполнено ДЗ №

 - [ 1 ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-12-12 12:39 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужно внести небольшие правки в манифесты пакера
В основном там не хватает пустых строк, по логах тестов все видно
ДЗ возвращаю на доработку

2022-12-13 05:17 UTC, sajor2006 commented
Подскажите в чем ошибка ?

2022-12-14 08:57 UTC, mrgreyves requested changes
Здравствуйте!)
![image](https://user-images.githubusercontent.com/34331259/207551214-7291112b-e86f-47b1-b241-7eb5ec788a49.png)
Например в конце не хвататет пустой строки
Кажется я описывал в чем проблема

2022-12-17 09:12 UTC, mrgreyves approved these changes
Здравствуйте!)
Перед мержем добавьте конфигурацию для хранения стейта в yandex S3 =)

2022-12-19 08:57 UTC, merged